// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251229111616_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is your first diary entry. Feel free to edit or delete it.",
                            Created = new DateTime(2025, 12, 29, 22, 16, 15, 744, DateTimeKind.Local).AddTicks(4706),
                            Title = "Welcome to Your Diary"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Start writing your thoughts and experiences here. Your diary is a safe space.",
                            Created = new DateTime(2025, 12, 29, 22, 16, 15, 744, DateTimeKind.Local).AddTicks(4709),
                            Title = "Getting Started"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Try to write regularly, be honest with yourself, and don't worry about grammar or spelling.",
                            Created = new DateTime(2025, 12, 29, 22, 16, 15, 744, DateTimeKind.Local).AddTicks(4712),
                            Title = "Tips for Writing"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Take a moment each day to reflect on what happened, how you felt, and what you learned.",
                            Created = new DateTime(2025, 12, 29, 22, 16, 15, 744, DateTimeKind.Local).AddTicks(4714),
                            Title = "Reflecting on Your Day"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
